name: Run Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # This cron expression runs the workflow every 6 hours
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      NYT_COOKIES_BASE64: ${{ secrets.NYT_COOKIES_BASE64 }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: python scraper.py

    - name: Configure Git
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add polls.csv
        git commit -m "Update polls.csv with new data"

    - name: Push changes
      uses: ad-m/github-push-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}